name: ci

on:
  push:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: ${{ secrets.REGISTRY_ADDRESS }}
      -
        name: Build and push - Core
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ secrets.REGISTRY_ADDRESS }}/article-recs:latest

      -
        name: Build and push - Content Summarization
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:modules/content_summarizer"
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ secrets.REGISTRY_ADDRESS }}/article-recs-summarizer:latest