name: Crawler
runs-on: self-hosted

on:

  push:
     branches: '*'

  schedule:
    - cron:  '0 */12 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.2.2'

      - name: Run Crawler
        run: | 
          poetry install 
          poetry run python ${GITHUB_WORKSPACE}/article_recs/crawler.py
          poetry run python ${GITHUB_WORKSPACE}/article_recs/crawler_reddit.py
          seq 5 | xargs -Iz poetry run python ${GITHUB_WORKSPACE}/article_recs/content_extractor.py
          seq 5 | xargs -Iz poetry run python ${GITHUB_WORKSPACE}/article_recs/candidate_generator.py
        env:
          POSTGRES_CONNECTION: ${{secrets.POSTGRES_CONNECTION}}
